spring:
  application:
    name: frontend-service
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

keycloak:
  auth-server-url: http://localhost:8180
  realm: bank

keycloak-admin:
  username: admin
  password: admin
  client-id: admin-cli
  client-secret: 

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.bank.frontend: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true