spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: frontend-service
          uri: http://localhost:8080
          predicates:
            - Path=/
        - id: authorization-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: accounts-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=2
        - id: accounts-service-test
          uri: http://localhost:8090
          predicates:
            - Path=/api/accounts/test
          filters:
            - StripPrefix=2
        - id: accounts-service-public
          uri: http://localhost:8090
          predicates:
            - Path=/api/accounts/public/**
          filters:
            - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.bank.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true